apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames:
  - ${FQDN}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ${FQDN}
  issuerRef:
    name: ${CERTIFICATE_PROVIDER}
    kind: ClusterIssuer
